// PingConfig.swift
// ⚠️  This file is auto-generated by the BXDemo Configurator
// ⚠️  Do not edit manually — use https://bxdemo-configurator.netlify.app
//
// Steps:
// 1. Go to https://bxdemo-configurator.netlify.app
// 2. Sign in with GitHub
// 3. Fill in your customer and PingOne configuration
// 4. Click Generate Config
// 5. Run: git fetch origin && git checkout demo/your-customer-slug
// 6. Build and run in Xcode

import Foundation

struct PingConfig {
    let environmentId: String
    let clientId: String
    let loginPolicyId: String
    let registrationPolicyId: String
    let stepUpPolicyId: String
    let redirectUri: String
    let scopes: [String]

    static let current = PingConfig(
        environmentId: "",
        clientId: "",
        loginPolicyId: "",
        registrationPolicyId: "",
        stepUpPolicyId: "",
        redirectUri: "bxdemo://callback",
        scopes: ["openid", "profile", "email"]
    )
}
