// CustomerConfig.swift
// Auto-generated by BXDemo Configurator
// Customer: Telemetry Solutions
// Generated: 2026-04-01T13:38:11.024Z

import SwiftUI

enum AuthMode {
    case davinci
    case oidcRedirect
}

struct ContentTile {
    let title: String
    let subtitle: String
    let icon: String
    enum TileAction { case navigate, stepUp }
    let action: TileAction
}

struct CustomerConfig {
    let appName: String
    let tagline: String
    let primaryColor: Color
    let secondaryColor: Color
    let buttonColor: Color
    let buttonBgColor: Color
    let footerBgColor: Color
    let homeBannerColor: Color
    let logoAssetName: String
    let bannerAssetName: String
    let vertical: String
    let customerSlug: String
    let authMode: AuthMode
    let contentTiles: [ContentTile]
    let stepUpTitle: String
    let stepUpSubtitle: String
}

extension CustomerConfig {
    static let current = CustomerConfig(
        appName: "Telemetry Solutions",
        tagline: "Telemetry for AI",
        primaryColor: Color(hex: "#000000"),
        secondaryColor: Color(hex: "#ff2929"),
        buttonColor: Color(hex: "#FFFFFF"),
        buttonBgColor: Color(hex: "#000000"),
        footerBgColor: Color(hex: "#000000"),
        homeBannerColor: Color(hex: "#ff2929"),
        logoAssetName: "telemetry-solutions-logo",
        bannerAssetName: "telemetry-solutions-banner",
        vertical: "technology",
        customerSlug: "telemetry-solutions",
        authMode: .oidcRedirect,
        contentTiles: [
        ContentTile(
            title: "Lap imes",
            subtitle: "Your ddfaf",
            icon: "qrcode",
            action: .stepUp
        ),
        ContentTile(
            title: "Rapid Rewards",
            subtitle: "You have 24,500 points — redeem for your next trip",
            icon: "star.fill",
            action: .navigate
        ),
        ContentTile(
            title: "Flight Deals",
            subtitle: "Exclusive member offers available now",
            icon: "heart.fill",
            action: .navigate
        ),
        ContentTile(
            title: "Travel Documents",
            subtitle: "Passport and security",
            icon: "lock.shield.fill",
            action: .stepUp
        )
        ],
        stepUpTitle: "Verify Your Identity",
        stepUpSubtitle: "This section requires additional verification"
    )
}
