// CustomerConfig.swift
// Auto-generated by BXDemo Configurator
// Customer: Insulet
// Generated: 2026-05-08T16:58:22.077Z

import SwiftUI

enum AuthMode {
    case davinci
    case oidcRedirect
}

struct ContentTile: Identifiable {
    let id = UUID()
    let title: String
    let subtitle: String
    let icon: String
    enum TileAction { case navigate, stepUp }
    let action: TileAction
}

struct CustomerConfig {
    let appName: String
    let tagline: String
    let primaryColor: Color
    let secondaryColor: Color
    let buttonColor: Color
    let buttonBgColor: Color
    let footerBgColor: Color
    let homeBannerColor: Color
    let logoAssetName: String
    let bannerAssetName: String
    let vertical: String
    let customerSlug: String
    let authMode: AuthMode
    let contentTiles: [ContentTile]
    let stepUpTitle: String
    let stepUpSubtitle: String
}

extension CustomerConfig {
    static let current = CustomerConfig(
        appName: "Insulet",
        tagline: "Simplify Life",
        primaryColor: Color(hex: "#8250c3"),
        secondaryColor: Color(hex: "#ffa700"),
        buttonColor: Color(hex: "#FFFFFF"),
        buttonBgColor: Color(hex: "#8250c3"),
        footerBgColor: Color(hex: "#8250c3"),
        homeBannerColor: Color(hex: "#ffa700"),
        logoAssetName: "insulet-logo",
        bannerAssetName: "insulet-banner",
        vertical: "healthcare",
        customerSlug: "insulet",
        authMode: .davinci,
        contentTiles: [
        ContentTile(
            title: "Reports",
            subtitle: "View your data",
            icon: "heart.text.square.fill",
            action: .navigate
        ),
        ContentTile(
            title: "Rapid Rewards",
            subtitle: "You have 24,500 points — redeem for your next trip",
            icon: "star.fill",
            action: .navigate
        ),
        ContentTile(
            title: "Review",
            subtitle: "Long term trends",
            icon: "tag.fill",
            action: .navigate
        ),
        ContentTile(
            title: "Documents",
            subtitle: "Review last information",
            icon: "lock.shield.fill",
            action: .stepUp
        )
        ],
        stepUpTitle: "Verify Your Identity",
        stepUpSubtitle: "This section requires additional verification"
    )
}
