// CustomerConfig.swift
// Auto-generated by BXDemo Configurator
// Customer: dfadf
// Generated: 2026-04-02T19:34:57.498Z

import SwiftUI

enum AuthMode {
    case davinci
    case oidcRedirect
}

struct ContentTile: Identifiable {
    let id = UUID()
    let title: String
    let subtitle: String
    let icon: String
    enum TileAction { case navigate, stepUp }
    let action: TileAction
}

struct CustomerConfig {
    let appName: String
    let tagline: String
    let primaryColor: Color
    let secondaryColor: Color
    let buttonColor: Color
    let buttonBgColor: Color
    let footerBgColor: Color
    let homeBannerColor: Color
    let logoAssetName: String
    let bannerAssetName: String
    let vertical: String
    let customerSlug: String
    let authMode: AuthMode
    let contentTiles: [ContentTile]
    let stepUpTitle: String
    let stepUpSubtitle: String
}

extension CustomerConfig {
    static let current = CustomerConfig(
        appName: "dfadf",
        tagline: "Without a heart, it's just a machine.",
        primaryColor: Color(hex: "#304CB2"),
        secondaryColor: Color(hex: "#FFBF27"),
        buttonColor: Color(hex: "#FFFFFF"),
        buttonBgColor: Color(hex: "#304CB2"),
        footerBgColor: Color(hex: "#304CB2"),
        homeBannerColor: Color(hex: "#FFBF27"),
        logoAssetName: "dfadf-logo",
        bannerAssetName: "dfadf-banner",
        vertical: "airlines",
        customerSlug: "dfadf",
        authMode: .davinci,
        contentTiles: [
        ContentTile(
            title: "My Trips",
            subtitle: "View and manage your upcoming flights",
            icon: "airplane",
            action: .stepUp
        ),
        ContentTile(
            title: "Rapid Rewards",
            subtitle: "You have 24,500 points — redeem for your next trip",
            icon: "star.fill",
            action: .stepUp
        ),
        ContentTile(
            title: "Flight Deals",
            subtitle: "Exclusive member offers available now",
            icon: "tag.fill",
            action: .stepUp
        ),
        ContentTile(
            title: "Travel Documents",
            subtitle: "Passport and security",
            icon: "lock.shield.fill",
            action: .stepUp
        )
        ],
        stepUpTitle: "Verify Your Identity",
        stepUpSubtitle: "This section requires additional verification"
    )
}
