// PingConfig.swift
// Auto-generated by BXDemo Configurator
// Customer: TelemetryDavinci
// Generated: 2026-04-01T16:50:48.355Z
// ⚠️  DO NOT COMMIT THIS FILE — it is listed in .gitignore

import Foundation

struct PingConfigValues {
    let environmentId: String
    let clientId: String
    let loginPolicyId: String
    let registrationPolicyId: String
    let stepUpPolicyId: String
    let oidcPolicyId: String
    let redirectUri: String
    let scopes: [String]
}

struct PingConfig {
    static var current = PingConfigValues(
        environmentId: "e08cdcdf-2389-418f-9064-aaa9ee4c5150",
        clientId: "78427c21-993e-4852-a05b-72e0139a41a2",
        loginPolicyId: "56f1907ce63e06dc0e9493ff1b72ba8e",
        registrationPolicyId: "01292a062d3e2960d2953f92849c6c17",
        stepUpPolicyId: "",
        oidcPolicyId: "",
        redirectUri: "bxdemo://callback",
        scopes: ["openid", "profile", "email"]
    )
}
