// PingConfig.swift
// Auto-generated by BXDemo Configurator
// Customer: Insulet
// Generated: 2026-05-08T16:58:22.077Z
// ⚠️  DO NOT COMMIT THIS FILE — it is listed in .gitignore

import Foundation

struct PingConfigValues {
    let environmentId: String
    let clientId: String
    let loginPolicyId: String
    let registrationPolicyId: String
    let stepUpPolicyId: String
    let oidcPolicyId: String
    let redirectUri: String
    let scopes: [String]
}

struct PingConfig {
    static var current = PingConfigValues(
        environmentId: "b8c6454a-d2cc-48ff-8b61-5349e721baf8",
        clientId: "2a1f819f-9713-46ef-9059-f8db884af7c3",
        loginPolicyId: "",
        registrationPolicyId: "",
        stepUpPolicyId: "",
        oidcPolicyId: "c6c8c86c447dce98177c2265512b651e",
        redirectUri: "bxdemo://callback",
        scopes: ["openid", "profile", "email"]
    )
}
