// PingConfig.swift
// Auto-generated by BXDemo Configurator
// Customer: Empire Consulting
// Generated: 2026-04-06T16:46:02.540Z
// ⚠️  DO NOT COMMIT THIS FILE — it is listed in .gitignore

import Foundation

struct PingConfigValues {
    let environmentId: String
    let clientId: String
    let loginPolicyId: String
    let registrationPolicyId: String
    let stepUpPolicyId: String
    let oidcPolicyId: String
    let redirectUri: String
    let scopes: [String]
}

struct PingConfig {
    static var current = PingConfigValues(
        environmentId: "80b9f0fb-d5d7-4d78-ba19-cd75b73c3fbf",
        clientId: "f9e69f6b-fd9e-475e-8850-0982be6e62f8",
        loginPolicyId: "7eece2957f316895ad0dbee1b56e0f04",
        registrationPolicyId: "815292eb6f04f26f9541315b4d870d60",
        stepUpPolicyId: "",
        oidcPolicyId: "",
        redirectUri: "bxdemo://callback",
        scopes: ["openid", "profile", "email"]
    )
}
